### ISSUE TITLE
Avoid binaries in git

### ISSUE THREAD

**Issue by stain** [gems-uff/prov-viewer#7]
https://github.com/gems-uff/prov-viewer/tree/master/lib contains three jar files of unknown origin:

* XMLInference.jar
* XMLInferenceNoOutput.jar
* jpl.jar

It is unclear of prov-viewer is open source as the license, source code and origin of these are unknown.

Fix is to use Maven for all dependencies and remove the jars.

**Comment by Kohwalter** [comment]
These were legacy code when prov viewer used prolog. These stopped being used and supported sometime ago. Though I had removed then from github as well. Thanks for the input.

**Comment by stain** [comment]
Thanks! :)
