### ISSUE TITLE
GitHub release?

### ISSUE THREAD

**Issue by stain** [gems-uff/prov-viewer#8]
https://github.com/gems-uff/prov-viewer/wiki/Installation says to download the release from a Dropbox link.

Dropbox links are notoriously unstable as well as might be blocked when Dropbox detects multiple downloads.

There are also no git tags for the release. 

I would recommend using https://github.com/gems-uff/prov-viewer/releases both for tagging and keeping the release downloads. This can also be combined with [Zenodo integration](https://guides.github.com/activities/citable-code/) to achieve a citable DOI per version.

**Comment by Kohwalter** [comment]
Thanks for the input.
The dropbox folder contains the program's jar ready for usage and requires no compilation.
Will start adding tags as well on github.

**Comment by stain** [comment]
https://help.github.com/articles/creating-releases/ says how to upload binaries together with the git tag.
